run-rec:
	clear
	gcc -o test bst.c rec_main.c stack.c
	./test

run-iter:
	clear
	gcc -o test bst.c iter_main.c stack.c
	./test

valgrind-rec:
	clear
	gcc -o test bst.c rec_main.c stack.c
	valgrind ./test

valgrind-iter:
	clear
	gcc -o test bst.c iter_main.c stack.c
	valgrind ./test